#!/usr/bin/env bash
# A script to generate for ascii to scancode set 2 mappings for azerty keyboards

count=127 # Index of the last entry to generate

declare -A SCANCODES
SCANCODES["1C"]="q"
SCANCODES["32"]="b"
SCANCODES["21"]="c"
SCANCODES["23"]="d"
SCANCODES["24"]="e"
SCANCODES["2B"]="f"
SCANCODES["34"]="g"
SCANCODES["33"]="h"
SCANCODES["43"]="i"
SCANCODES["3B"]="j"
SCANCODES["42"]="k"
SCANCODES["4B"]="l"
SCANCODES["76"]="m"
SCANCODES["31"]="n"
SCANCODES["44"]="o"
SCANCODES["4d"]="p"
SCANCODES["15"]="a"
SCANCODES["2D"]="r"
SCANCODES["1B"]="s"
SCANCODES["2C"]="t"
SCANCODES["3C"]="u"
SCANCODES["2A"]="v"
SCANCODES["1D"]="z"
SCANCODES["22"]="x"
SCANCODES["35"]="y"
SCANCODES["1A"]="w"
SCANCODES["45"]="0"
SCANCODES["16"]="1"
SCANCODES["1E"]="2"
SCANCODES["26"]="3"
SCANCODES["25"]="4"
SCANCODES["2E"]="5"
SCANCODES["36"]="6"
SCANCODES["3D"]="7"
SCANCODES["3E"]="8"
SCANCODES["46"]="9"

SCANCODES["3A"]=","
SCANCODES["66"]="\\b"

SCANCODES["29"]=" "
SCANCODES["5A"]="\\n"

gen ()
{
  printf "// This file is autogenerated by the scancodes2ascii.sh script.\nchar ScanCodeSet2ToAsciiTable[$(($count + 1))] = {"
  for i in $(seq 0 $count) ; do
    hex=$(printf "%02X" "$i")

    scan_code="${SCANCODES["$hex"]}"
    if ! [ -z "$scan_code" ] ; then
      echo -n "'$scan_code',"
    else
      echo -n "'\\0',"
    fi
  done
  printf "\n};"
}

gen > scancodes2ascii.h
